# Generated by Django 2.2.8 on 2020-04-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_suggested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
