# Generated by Django 2.2.8 on 2020-04-06 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200404_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catlist',
            fields=[
                ('catlist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('catlist_summary', models.CharField(max_length=1000000)),
                ('catlist_title', models.CharField(max_length=500)),
                ('catlist_logo', models.FileField(upload_to='')),
                ('catlist_author', models.CharField(max_length=500)),
                ('catlist_date', models.CharField(max_length=500)),
                ('catlist_url', models.IntegerField()),
                ('catlist_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
        ),
    ]
