# Generated by Django 2.2.8 on 2020-04-06 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_catlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tech',
            old_name='hotnews_url',
            new_name='tech_url',
        ),
    ]
