# Generated by Django 3.0.5 on 2020-04-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200407_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_logo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='catlist',
            name='catlist_logo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='editor',
            name='editor_logo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='hotnews',
            name='hotnews_logo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='suggested',
            name='suggested_logo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tech',
            name='tech_logo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='trending',
            name='trending_logo',
            field=models.CharField(max_length=500),
        ),
    ]
