# Generated by Django 3.0.5 on 2020-05-02 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('set_id', models.IntegerField(primary_key=True, serialize=False)),
                ('set_question1', models.TextField(blank=True, null=True)),
                ('set_ansnwer1', models.CharField(max_length=500)),
                ('set_img1', models.CharField(max_length=500)),
                ('set_question2', models.TextField(blank=True, null=True)),
                ('set_ansnwer2', models.CharField(max_length=500)),
                ('set_img2', models.CharField(max_length=500)),
                ('set_question3', models.TextField(blank=True, null=True)),
                ('set_ansnwer3', models.CharField(max_length=500)),
                ('set_img3', models.CharField(max_length=500)),
                ('set_question4', models.TextField(blank=True, null=True)),
                ('set_ansnwer4', models.CharField(max_length=500)),
                ('set_img4', models.CharField(max_length=500)),
                ('set_question5', models.TextField(blank=True, null=True)),
                ('set_ansnwer5', models.CharField(max_length=500)),
                ('set_img5', models.CharField(max_length=500)),
                ('set_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
        ),
    ]
