# Generated by Django 3.0.5 on 2020-05-04 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_sets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sets',
            old_name='set_ansnwer1',
            new_name='set_answer1',
        ),
        migrations.RenameField(
            model_name='sets',
            old_name='set_ansnwer2',
            new_name='set_answer2',
        ),
        migrations.RenameField(
            model_name='sets',
            old_name='set_ansnwer3',
            new_name='set_answer3',
        ),
        migrations.RenameField(
            model_name='sets',
            old_name='set_ansnwer4',
            new_name='set_answer4',
        ),
        migrations.RenameField(
            model_name='sets',
            old_name='set_ansnwer5',
            new_name='set_answer5',
        ),
    ]
