# Generated by Django 3.0.5 on 2020-05-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200505_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='sets',
            name='set_date',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sets',
            name='set_topic',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
