# Generated by Django 3.0.5 on 2020-05-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200505_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sets',
            name='set_question1',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
