# Generated by Django 3.0.5 on 2020-05-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200519_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_text2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
